doc: actually package generated documentation
Previous find command wouldn't actually list the generated documentation
files, so they'd be missing in the tarball.

...and add a dist-hook to make sure this won't happen during release.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
Reviewed-by: Benjamin Tissoires <benjamin.tissoires@gmail.com>

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -9,8 +9,17 @@ clean-local:
 
 .PHONY: doxygen
 
-doc_src= $(shell find . -name "html" -printf "%P\n")
+doc_src= $(shell find html -name "*" -printf "html/%P\n")
 EXTRA_DIST = $(doc_src) libevdev.doxygen libevdev.css
 endif
 
 dist_noinst_DATA = libevdev.doxygen.in
+
+# make sure doc was built before running dist
+dist-hook:
+	@test -f $(distdir)/html/index.html || (\
+		echo "******************************************************" && \
+		echo "Couldn't find documentation files, refusing make dist." && \
+		echo "Install doxygen to build documentation for tarball." && \
+		echo "******************************************************" && \
+		test )
